failure-threshold: style
ignored:
  # repository pinning is better than package pinning for apk
  # https://stschindler.medium.com/the-problem-with-docker-and-alpines-package-pinning-18346593e891
  - DL3018
  # shellcheck doesn't recognize the SHELL sh -eux command
  - DL4006
label-schema:
  org.opencontainers.image.authors: text
  org.opencontainers.image.source: url
  org.opencontainers.image.licences: spdx
strict-labels: true
